---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "ppa:otto-kesselgulasch/gimp" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "gimp" }
        - { state: "latest", name: "gimp-data" }
        - { state: "latest", name: "gimp-data-extras" }
        - { state: "latest", name: "gimp-gap" }
        - { state: "latest", name: "gimp-help-en" }
        - { state: "latest", name: "gimp-help-ja" }
        - { state: "latest", name: "gimp-help-ko" }
