---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", repo: "ppa:mozillateam/thunderbird-next" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "thunderbird" }
        - { state: "latest", name: "thunderbird-gnome-support" }
        - { state: "latest", name: "thunderbird-locale-en" }
        - { state: "latest", name: "thunderbird-locale-en-gb" }
        - { state: "latest", name: "thunderbird-locale-en-us" }
        - { state: "latest", name: "thunderbird-locale-ja" }
        - { state: "latest", name: "thunderbird-locale-ko" }
        - { state: "latest", name: "thunderbird-locale-zh-cn" }
        - { state: "latest", name: "thunderbird-locale-zh-hans" }
        - { state: "latest", name: "thunderbird-locale-zh-hant" }
        - { state: "latest", name: "thunderbird-locale-zh-tw" }
        - { state: "latest", name: "xul-ext-lightning" }
